apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis-fox-deployment
spec:
  selector:
    matchLabels:
      app: redis-fox
  replicas: 1
  template:
    metadata:
      labels:
        app: redis-fox
    spec:
      containers:
        - name: redis-fox
          image: redis
          imagePullPolicy: Always
          command:
            - "redis-server"
          ports:
            - containerPort: 6379
              protocol: TCP
          volumeMounts:
            - name: redis-persistent-storage
              mountPath: /var/lib/redis           #要对这个目录做数据持久化
      volumes:
        - name: redis-persistent-storage
          persistentVolumeClaim:
            claimName: redis-pvc       #指定pvc的名称
---
apiVersion: v1
kind: Service
metadata:
  name: redis-fox
spec:
  ports:
    - name: redis-fox-port
      protocol: TCP
      port: 6379
      targetPort: 6379
      nodePort: 31379
  type: NodePort
  selector:
    app: redis-fox

