apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql-fox-deployment
spec:
  selector:
    matchLabels:
      app: mysql-fox
  replicas: 1
  template:
    metadata:
      labels:
        app: mysql-fox
    spec:
      containers:
        - name: mysql-fox
          image: mysql
          imagePullPolicy: Always
          env:                        #以下是设置MySQL数据库的密码
            - name: MYSQL_ROOT_PASSWORD
              value: "123456"
          ports:
            - containerPort: 3306
              protocol: TCP
          volumeMounts:
            - name: mysql-persistent-storage
              mountPath: /var/lib/mysql           #MySQL容器的数据都是存在这个目录的，要对这个目录做数据持久化
            - name: config-volume
              mountPath: /etc/mysql/conf.d             #mysql 配置
      volumes:
        - name: mysql-persistent-storage
          persistentVolumeClaim:
            claimName: mysql-pvc       #指定pvc的名称
        - name: config-volume
          configMap:
            name: mysql-config
---
apiVersion: v1
kind: Service
metadata:
  name: mysql-fox
spec:
  ports:
    - name: mysql-fox-port
      protocol: TCP
      port: 3306
      targetPort: 3306
      nodePort: 31306
  type: NodePort
  selector:
    app: mysql-fox
